openapi: 3.0.0
info:
  title: Flight-Sim-Logbook API
  description: API definition for the flight simulation logbook web app's REST API.
  version: 0.1.0
servers:
  - url: https://flight-sim-logbook.herokuapp.com/api/
paths:
  /logbooks/create:
    post:
      summary: Creates a user account and sends a verification email.
      tags:
        - Logbooks
      requestBody:
        description: Details of the logbook to create
        content:
          application/json:
            schema:
              type: object
              properties:
                aircraftName:
                  type: string
                  description: The name of the aircraft
        required: true
      responses:
        "201": # status code
          description: Basic details of the created user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  logbook:
                    type: object
                    properties:
                      aircraft:
                        type: string
                        description: The name of the aircraft
                      totalHours:
                        type: number
                        description: The overall number of hours flown
                      imcHours:
                        type: number
                        description: The number of hours in instrument meteorological conditions
                      bfmHours:
                        type: number
                        description: The number of hours in basic fighter manoeuvres
                      bvrHours:
                        type: number
                        description: The number of hours in beyond visual range combat
                      seadHours:
                        type: number
                        description: The number of hours in the SEAD role
                      casHours:
                        type: number
                        description: The number of hours in the close air support role
                      strikeHours:
                        type: number
                        description: The number of hours in the precision strike role
                      packageHours:
                        type: number
                        description: The number of hours working as part of a coordinated package
                      caseISorties:
                        type: number
                        description: The number of Case I carrier sorties
                      caseIIISorties:
                        type: number
                        description: The number of Case III carrier sorties
                      aarHours:
                        type: number
                        description: The number of hours doing air-to-air refueling
                  errors:
                    type: array
                    items:
                      type: string
        "400": # status code
          description: Invalid request (user alread has a logbook for the given aircraft, aircraft name is invalid, etc.)
          content:
            application/json:
              schema:
                type: object
                properties:
                  logbook:
                    type: object
                    description: This will be null
                  errors:
                    type: array
                    items:
                      type: string
        "500": # status code
          description: An unexpected server-side error
          content:
            application/json:
              schema:
                type: object
                properties:
                  logbook:
                    type: object
                    description: This will be null
                  errors:
                    type: array
                    items:
                      type: string

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
