const LOGIN = "LOGIN";
const REGISTER = "REGISTER";
const LOGOUT = "LOGOUT";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";

export { LOGIN, REGISTER, LOGOUT, SET_ALERT, REMOVE_ALERT };
