const LOGIN = "LOGIN";
const CHECK_LOGIN_STATUS = "CHECK_LOGIN_STATUS";
const REGISTER = "REGISTER";
const LOGOUT = "LOGOUT";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";

export { LOGIN, CHECK_LOGIN_STATUS, REGISTER, LOGOUT, SET_ALERT, REMOVE_ALERT };
