    openapi: 3.0.0
    info:
      title: Flight-Sim-Logbook API
      description: API definition for the flight simulation logbook web app's REST API.
      version: 0.1.0
    servers:
      - url: https://flight-sim-logbook.herokuapp.com/api/
    paths:
      /users/create:
        post:
          summary: Creates a user account and sends a verification email.
          requestBody:
            description: Details of the user to create
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                      description: The username
                    email:
                      type: string
                      description: The user's email address
                    password:
                      type: string
                      description: The desired password
                    passwordConfirmation:
                      type: string
                      description: Confirmation of the password
            required: true
          responses:
            '201':    # status code
              description: Basic details of the created user.
              content:
                application/json:
                  schema: 
                    type: object
                    properties: 
                      user:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The user's name
                          email:
                            type: string
                            description: The user's email address
                      errors:
                        type: array
                        items:
                          type: string
            '400':    # status code
              description: Invalid request (mismatched password confirmation, user already exists, etc.)
              content:
                application/json:
                  schema: 
                    type: object
                    properties: 
                      user:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The user's name
                          email:
                            type: string
                            description: The user's email address
                      errors:
                        type: array
                        items:
                          type: string
            '500':    # status code
              description: An unexpected server-side error
              content:
                application/json:
                  schema: 
                    type: object
                    properties: 
                      user:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The user's name
                          email:
                            type: string
                            description: The user's email address
                      errors:
                        type: array
                        items:
                          type: string
      /users/login:
        post:
          summary: Creates a user account and sends a verification email.
          requestBody:
            description: Details of the user to log in
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    name:
                      type: string
                      description: The username
                    password:
                      type: string
                      description: The password for the user
            required: true
          responses:
            '200':    # status code
              description: Basic details of the created user.
              content:
                application/json:
                  schema: 
                    type: object
                    properties: 
                      jwt:
                        type: string
                        description: The login token, to be used as a Bearer Authorization token in subsequent requests.
            '401':    # status code
              description: Invalid credentials (user email not verified, incorrect password, etc.)
              content:
                application/json:
                  schema: 
                    type: object
                    properties: 
                      errors:
                        type: array
                        items:
                          type: string
            '500':    # status code
              description: An unexpected server-side error
              content:
                application/json:
                  schema: 
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          type: string
                      