const LOGIN = "LOGIN";
const CHECK_LOGIN_STATUS = "CHECK_LOGIN_STATUS";
const REGISTER = "REGISTER";
const LOGOUT = "LOGOUT";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const CREATE_LOGBOOK = "CREATE_LOGBOOK";
const GET_LOGBOOKS = "GET_LOGBOOKS";
const GET_LOGBOOK = "GET_LOGBOOK";
const DELETE_LOGBOOK = "DELETE_LOGBOOK";
const SELECT_LOGBOOK = "SELECT_LOGBOOK";
const ADD_MISSION = "ADD_MISSION";
const GET_ALL_AIRCRAFT = "GET_ALL_AIRCRAFT";

export {
  LOGIN,
  CHECK_LOGIN_STATUS,
  REGISTER,
  LOGOUT,
  SET_ALERT,
  REMOVE_ALERT,
  CREATE_LOGBOOK,
  GET_LOGBOOKS,
  GET_LOGBOOK,
  DELETE_LOGBOOK,
  SELECT_LOGBOOK,
  LOG_MISSION,
  GET_ALL_AIRCRAFT,
};
